# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aafd3e1c62e2d26a7fd67bfea345208b5a9f957dabebc619539207ac5d4265ac7bddf98bcf2296eba58bf5176cb6ed2b62d88ba5189dc731c1fafbf7574c9bf4

test:
  secret_key_base: d8dcf2fdcb98f18152e7e6ea52a4c6a0957829a173b0bd6432aa4a65dca3979adeb4d949fb75ce9a84de168a75f9db278b22c15e2852f5178c0abf99a621442c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
